### ISSUE TITLE
Zero Length subscriber_file

### ISSUE THREAD

**Issue by tsawyer** [n0mjs710/hblink3#17]
A zero length subscriber_file causes the below error and prevents hblink3 startup. Simple work around is to delete subscriber_ids.json and restart. Looks like the error is thrown by dmr_utils3 but perhaps a check in bridge.py would be appropriate. 

`/usr/bin/python3 /opt/HBLink3/bridge.py -c /etc/hblink/hblink3.cfg
Traceback (most recent call last):
  File "/opt/HBLink3/bridge.py", line 772, in <module>
    peer_ids, subscriber_ids, talkgroup_ids = mk_aliases(CONFIG)
  File "/opt/HBLink3/hblink.py", line 751, in mk_aliases
    subscriber_ids = mk_id_dict(_config['ALIASES']['PATH'], _config['ALIASES']['SUBSCRIBER_FILE'])
  File "/usr/local/lib/python3.7/dist-packages/dmr_utils3/utils.py", line 97, in mk_id_dict
    records = jload(_handle)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by n0mjs710** [comment]
I'm actually quite happy that a zero length subscriber ID file causes an error.
